# Generated by Django 4.2.2 on 2023-08-16 07:34

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='color_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_profile', models.CharField(default='profile01', max_length=64, verbose_name='Название профиля')),
                ('name_site', models.CharField(default='Сайт', max_length=255, verbose_name='Название сайта')),
                ('left_padding', models.IntegerField(default=0, help_text='Регулировка левого отступа, пользовательская модификация', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Левый отступ, % от экрана')),
                ('title_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет заголовков')),
                ('hover_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Фон при наведении на подпункты меню')),
                ('hover_files', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Фон при наведении на файлы')),
                ('text_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет основного текста')),
                ('menu_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет фона меню и обводок')),
                ('menu_text_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Цвет текста меню')),
                ('background_color', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None, verbose_name='Фон сайта')),
                ('pos_code', models.TextField(default='', verbose_name='Код для интеграции ПОС Госуслуги')),
                ('onmenu', models.BooleanField(default=False, help_text='Отключить меню/включить', verbose_name='Меню на странице')),
            ],
            options={
                'verbose_name': 'Глобальные настройки сайта',
                'verbose_name_plural': 'Глобальные настройки сайта',
            },
        ),
    ]
