# Generated by Django 4.2.2 on 2023-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiucolors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color_profile',
            name='yandex_meta',
            field=models.CharField(default='', max_length=255, verbose_name='ID верификации в Яндексе'),
        ),
    ]
