# Generated by Django 4.2.2 on 2023-08-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiuExtParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_profile', models.CharField(default='extended01', max_length=64, verbose_name='Профиль расширенных управлений')),
                ('disMenuClick', models.BooleanField(default=False, verbose_name='Отключить переходы по меню')),
                ('disMenuMove', models.BooleanField(default=False, verbose_name='Отключить наведение=клик')),
                ('enPreloader', models.BooleanField(default=False, verbose_name='Включить прелоадер')),
                ('dMode', models.BooleanField(default=False, verbose_name='Активировать DEBUG mode')),
            ],
            options={
                'verbose_name': 'Расширенное администрирование (в разработке)',
                'verbose_name_plural': 'Расширенное администрирование (в разработке)',
            },
        ),
    ]
