# Generated by Django 4.2.2 on 2023-08-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('base_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Базовый URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=500, verbose_name='Приоритет')),
                ('link_url', models.CharField(help_text='URL или URI к странице, /about/ или http://yandex.ru/', max_length=100, verbose_name='Ссылка')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('login_required', models.BooleanField(blank=True, default=False, help_text='Должен ли этот элемент отображаться только авторизованным пользователям?', verbose_name='Авторизация пользователя')),
                ('anonymous_only', models.BooleanField(blank=True, default=False, help_text='Видит ли этот элемент анонимный пользователь?', verbose_name='Анонимный юзер')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aiumenus.menu', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Элементы меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
    ]
