# Generated by Django 4.2.2 on 2023-08-24 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiupages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Заголовок для блока', max_length=255, verbose_name='Заголовок (если необходим)')),
                ('blockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiupanels', to='aiupages.blocks')),
            ],
            options={
                'verbose_name': 'Панель блок ссылок',
                'verbose_name_plural': 'Панель блок ссылок',
            },
        ),
        migrations.CreateModel(
            name='PanelBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.CharField(blank=True, default='', help_text='Ссылка для открытия', max_length=255, verbose_name='Ссылка')),
                ('nowpage', models.BooleanField(default=True, help_text='Выбор открывать ссылку в новой вкладке или с перезагрузкой в текущей, для пользователей практично в новой вкладке', verbose_name='Открывать ссылку в новой вкладке')),
                ('title', models.CharField(blank=True, default='', help_text='Выводимый текст для ссылки', max_length=255, verbose_name='Текст')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше приоритет, как порядковый номер', verbose_name='Приоритет отображения')),
                ('panelid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aiupanelblock', to='aiupages.panelsblock')),
            ],
            options={
                'verbose_name': 'Элементы панели',
                'verbose_name_plural': 'Элементы панели',
            },
        ),
    ]
