# Generated by Django 4.2.2 on 2023-08-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiupages', '0002_panelsblock_panelblockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelblockitem',
            name='panelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelblock_item', to='aiupages.panelsblock'),
        ),
        migrations.AlterField(
            model_name='panelsblock',
            name='blockid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelsblock_cont', to='aiupages.blocks'),
        ),
    ]
