# Generated by Django 4.2.2 on 2023-08-29 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aiupages', '0003_alter_panelblockitem_panelid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='panelblockitem',
            options={'ordering': ['order'], 'verbose_name': 'Элементы панели', 'verbose_name_plural': 'Элементы панели'},
        ),
        migrations.CreateModel(
            name='UsersBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Заголовок блока', max_length=255, verbose_name='Заголовок')),
                ('blockid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileview', to='aiupages.blocks')),
            ],
            options={
                'verbose_name': 'Отобразить профиль пользователя',
                'verbose_name_plural': 'Отобразить профиль пользователя',
            },
        ),
    ]
