# Generated by Django 4.2.2 on 2023-08-29 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aiupages', '0004_alter_panelblockitem_options_usersblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='О себе, например биография и прочее', null=True, verbose_name='О себе')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile-avatar/')),
                ('vkid', models.CharField(blank=True, help_text='Свой VK для связи', max_length=50, null=True, verbose_name='Свой ВК')),
                ('userid', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профили пользователей',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
