# Generated by Django 4.2.2 on 2023-08-31 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiupages', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
